package main

import (
  "net/http"
  "github.com/users"
)



func main()  {

  http.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
  http.HandleFunc("/", Datas.Index)
  defer Datas.CloseClientDB()
  http.HandleFunc("/serviceworker.js", Datas.SendSW)
	http.HandleFunc("/manifest.json", Datas.SendManifest)
  http.HandleFunc("/googlelogin", Datas.HandleGoogleLogin)
  http.HandleFunc("/callback", Datas.HandleGoogleCallback)
  http.HandleFunc("/logout", Datas.Logout)   //will be modified
  http.HandleFunc("/setting", Datas.Setting)
  http.HandleFunc("/updateSetting", Datas.UpdateSetting)
  http.HandleFunc("/updatelick", Datas.Updatelick)
  http.HandleFunc("/updatelickscale", Datas.UpdateLickScale)
  http.HandleFunc("/updatelickkey", Datas.UpdateLickKey)
  http.HandleFunc("/updatelickname", Datas.UpdateLickName)
  http.HandleFunc("/getSheetData", Datas.GetSheetData)
  http.HandleFunc("/newlick", Datas.NewLick)
  http.HandleFunc("/deleteLick", Datas.DeleteLick)
  http.HandleFunc("/newsheet", Datas.NewSheet)
  http.HandleFunc("/sheetnewlick", Datas.SheetNewEmptyLick)
  http.HandleFunc("/switchsheetlicks", Datas.SwitchSheetLicks)
  http.HandleFunc("/updatesheet", Datas.UpdateSheet)
  http.HandleFunc("/deleteSheet", Datas.DeleteSheet)
  http.HandleFunc("/updatesheettitle", Datas.UpdateSheetTitle)
  http.HandleFunc("/updatesheetlickkey", Datas.UpdateSheetLickKey)
  http.HandleFunc("/updatesheetkey", Datas.UpdateSheetKey)
  //http.HandleFunc("/sharelicks", licks)
  //http.HandleFunc("/sharesheets", sheets)
  http.HandleFunc("/mylicks", Datas.MyLicks)
  http.HandleFunc("/loadmylicks", Datas.LoadMyLicks)
  http.HandleFunc("/Ldisplay", Datas.DisplayLicks)
  http.HandleFunc("/SLdisplay", Datas.EditLicks)
  http.HandleFunc("/mysheets", Datas.MySheets)
  http.HandleFunc("/Sdisplay", Datas.DisplaySheets)
  http.HandleFunc("/forum", Datas.Forum)
  http.HandleFunc("/Fdisplay", Datas.DisplayForum)
  http.HandleFunc("/getPosts", Datas.GetPosts)
  http.HandleFunc("/getComments", Datas.GetComments)
  http.HandleFunc("/postComments", Datas.PostComments)
  http.HandleFunc("/delCom", Datas.DelCom)
  http.HandleFunc("/saveCom", Datas.SaveCom)
  http.HandleFunc("/postpost", Datas.PostPost)
  http.HandleFunc("/votePost", Datas.VotePost)
  http.HandleFunc("/visitpost", Datas.VisitPost)
  http.HandleFunc("/visitprofile", Datas.VisitProfile)
  http.HandleFunc("/visitlick", Datas.VisitLick)
  http.HandleFunc("/vpfl", Datas.VPFL)
  http.HandleFunc("/vpfs", Datas.VPFS)
  http.HandleFunc("/vpfe", Datas.VPFE)
  http.HandleFunc("/follow", Datas.Follow)
  http.HandleFunc("/unfollow", Datas.Unfollow)
  http.HandleFunc("/sharelicks", Datas.ShareLicks)
  http.HandleFunc("/getSharedLicks", Datas.GetSharedLicks)
  http.HandleFunc("/dlsl", Datas.Dlsl)
  http.HandleFunc("/dlss", Datas.Dlss)
  http.HandleFunc("/sharesheets", Datas.ShareSheets)
  http.HandleFunc("/getSharedSheets", Datas.GetSharedSheets)
  http.HandleFunc("/visitsheet", Datas.VisitSheet)
  http.HandleFunc("/users", Datas.UserList)
  http.HandleFunc("/getUserslist", Datas.GetUsersList)
  http.HandleFunc("/cp", Datas.CallPayment)
  http.HandleFunc("/goPro", Datas.GoPro)
  http.HandleFunc("/sk", Datas.SK)
  http.HandleFunc("/ckpy", Datas.CheckPayment)
  http.HandleFunc("/feedbackurl", Datas.Feedback)
  http.HandleFunc("/terms", Datas.Terms)
  http.HandleFunc("/editPost", Datas.EditPost)
  http.HandleFunc("/deletePost", Datas.DeletePost)
  //http.HandleFunc("/forum", forum)
  http.Handle("/favicon.ico", http.NotFoundHandler())
  http.ListenAndServe(":8080", nil)
}
